### ISSUE TITLE
Redesign how JBomb works

### ISSUE THREAD

**Issue by trhgquan** [trhgquan/JBomb#10]
We cannot just doing 2-loops way like this. Here are some "small" changes:

- [x] [Redesign how to count bombs around the cells.](https://github.com/trhgquan/JBomb/issues/12)

- [x] [Redesign how to count defused bombs.](https://github.com/trhgquan/JBomb/issues/13)

- [x] [Redesign how we show location of the bombs.](https://github.com/trhgquan/JBomb/issues/14)

- [x] [Redesign how we know that the game is finished.](https://github.com/trhgquan/JBomb/issues/15)

That's all changes scheduled.

@meadoge

**Comment by meadoge** [comment]
This should be split into many small issues, each of them about a different method, since resolve all in 1 commit it somehow impossible.

We will go further after #9 resolved. Until that please split this issue into smaller issues and tag me in.

Regards,

**Comment by meadoge** [comment]
And this list should includes `Show locations of the bombs` and `How the game is finished` too, since these procedure is using 2 for-loops which can be reduced into using only 1 loop.

As I said, split this issue into small issues, link them here and edit the list. That way we can easily trace the progresses and commits of each small issue.

Regards,

**Comment by trhgquan** [comment]
Checkbox updated, sorry for my mistakes!

I'll finish those issues tomorrow.

**Comment by meadoge** [comment]
@trhgquan Please update all links in the issue, thank you.

**Comment by trhgquan** [comment]
Links updated.

**Comment by meadoge** [comment]
All tasks done.

@trhgquan

**Comment by trhgquan** [comment]
Great, let me do some tests and response to you.

**Comment by trhgquan** [comment]
This issue is done. @meadoge please create a PR for final.
